### ISSUE TITLE
Instructions on how to build

### ISSUE THREAD

**Issue by onny** [L11R/go-autoconfig#1]
Would be helpful if you could instructions on how to build :) I'm not so familiar with Go projects yet.

Regards
Jonas

**Comment by savely-krasovsky** [comment]
`go build -o server main.go`

**Comment by onny** [comment]
Hey @L11R thanks for your nice project :)
I'm currently trying to package it for NixOS https://github.com/NixOS/nixpkgs/pull/184973 and here the specific package script https://github.com/NixOS/nixpkgs/blob/37a1ccc15c024f662afeea89120dc64e5fb0db76/pkgs/servers/go-autoconfig/default.nix
Somehow NixOS was missing go.sum so I cloned the source and ran `go mod tidy`.
After that I added the diff as a patch file for the NixOS build instructions and it went well with updated `go.mod` dependencies and `go.sum` file. Maybe you could include that into your repo?
Not sure if this is the correct way.

Regards
Jonas

ps.
I'm experimenting using your project as a NixOS module for a simple mail server setup https://nixos.wiki/wiki/Maddy#Autoconfig

**Comment by savely-krasovsky** [comment]
@onny done. Also project was updated to use Echo v4 where was fixed some unrelated security vulnerabilities.
